- name: Set hostname
  become: yes
  hostname:
    name: '{{ inventory_hostname }}'

- name: Update name server
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ item }}"
  with_items: "{{name_server}}"
  tags: nameserver

- name: Install basic packages for Debian specify
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "{{ defaultpackage }}"

- name: Change pi password
  user:
    name: pi
    password: "$6$9JEfAqST$rtm8xJVIroMvR3TTnJmjtdPlEtFRzeRzmO8aEid3.MeYOwxVR4KJ5EUfarFeL0nlC.WDhsXBGX.qdREXbCDfX/"
  tags: password

- name: Change Logrotate rules
  template:
    src: "{{role_path}}/files/logrotate.conf"
    dest: /etc/logrotate.conf
  tags: logrotate

- name: Change keyboard layout
  become: yes
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT="hk"'
    line: 'XKBLAYOUT="us"'

- name: Change Wifi config
  become: yes
  template:
    src: "{{role_path}}/files/wpa_supplicant.j2"
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  tags: wifi

- name: SSH authorized_key
  become: yes
  authorized_key: 
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Reboot server
  shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  when: reboot == "yes"

- name: Wait for server to ping up
  local_action: wait_for host={{ ansible_host }}
                        state=started
                        port=22
                        delay=15
                        timeout={{ timeout }}
                        connect_timeout=15
  when: reboot == "yes"

